export const keywords = [
  'meta',
  'metaverse',
  'meta nft',
  'metafolks',
  'meta folks',
  'folks',
  'nft',
  'nfts',
  'art',
  'nftart',
  'nftartist',
  'nftcollector',
  'nftcollectors',
  'nftcommunity',
  'nftdrop',
  'nftdrops',
  'nftgiveaway',
  'nftproject',
  'polygonnft',
  'polygon',
  'maticnft',
  'cryptopunks',
  'bored ape yacht club',
  'doodles',
  'jungle freaks by trosley',
  'boonji project',
  'kaiju kingz',
  'crypto punks',
  'cyberkongs',
  'cool cats nft',
  'mekaverse',
  'mutantcats',
  'mint',
  'mintable',
  'mint nft',
]
